spring.application.name=jpa-member-1

#=================
# postgreSQL 연결
#=================
spring.datasource.url=jdbc:postgresql://localhost:5432/hrd
spring.datasource.username=postgres
spring.datasource.password=1234

#=================
# JPA 설정
#=================
# Etity클래스를 기분으로 테이블 자동 생성 및 수정.
spring.jpa.hibernate.ddl-auto=update

# 런타임에 SQL쿼리를 콘솔에 출력
spring.jpa.show-sql=true

# Entity의 카멜케이스 클래스명() -> 변환시킴(소문자_테이블명으로)
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy


#=================
# Swagger 설정
#=================

