spring.application.name=try-mybatis

# postgrSQL 설정
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/hrd
spring.datasource.username=postgres
spring.datasource.password=1234

# MyBatis 설정
mybatis.mapper-locations=classpath:/mapper/*.xml
mybatis.type-aliases-package=com.skc.dto
# student_name를 자동으로 studentName로 변환(DB 오류대비)
#mybatis.configuration.map-underscore-to-camel-case=true

# SQL 로그 출력
mybatis.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl

# Spring 로그 범위설정
logging.level.root=INFO
logging.level.org.springframework=INFO
logging.level.com.skc=DEBUG

# DevTools
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true

# 개발중 에러 메시지
server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=always

# Thymeleaf(캐시)
spring.thymeleaf.cache=false