spring.application.name=try-mybatis-2

# postgrSQL 설정
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/hrd
spring.datasource.username=postgres
spring.datasource.password=1234

# MyBatis 설정
mybatis.config-location=classpath:mybatis/mybatis-config.xml
mybatis.mapper-locations=classpath:mybatis/mapper/*.xml
mybatis.type-aliases-package=com.skc.dto
# student_name를 자동으로 studentName로 변환(DB 오류대비)
#mybatis.configuration.map-underscore-to-camel-case=true